import Link from "next/link"
import "./globals.css"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const header = (
  <header>
    <div>
      <Link href="/">
      <h1>fifolio blog</h1>
      </Link>
      <p>Welcome to my blog space</p>
      <br />
    </div>
  </header>
)

const footer = (
  <footer>
    <div>
      <br />
      <h3>Developed by fifolio</h3>
    </div>
  </footer>
)

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
        {header}
        {children}
        {footer}
        </body>
    </html>
  )
}
