import Link from "next/link"
import "./globals.css"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const header = (
  <header>
    <div className="text-center bg-slate-800 p-10 my-6 rounded-md">
      <Link href="/">
      <h1 className="text-3xl font-bold text-white">fifolio blog</h1>
      </Link>
      <p className="text-slate-300">🖐️ Welcome to my blog space 💻</p>
    </div>
  </header>
)

const footer = (
  <footer>
    <div className="border-t border-slate-400 mt-6 py-6 text-center text-gray-500">
      <h3>Developed by fifolio</h3>
    </div>
  </footer>
)

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
        <div className="mx-auto max-w-2xl px-6">
        {header}
        {children}
        {footer}
        </div>
        </body>
    </html>
  )
}
